---
# chocomilk vars

# Package Changelog
changelog: 'https://release-monitoring.org/api/v2/projects/?name=Veeam%20Agent'

# Regex for Version
version: "{{ register_changelog.json['items'][0]['version'] }}"

# Download URL
url: 'https://download5.veeam.com/VeeamAgentWindows_{{ version }}.zip'
# url64:

searchreplace:
  'tools/chocolateyinstall.ps1':
    - regwxp: (^\s*[$]*url\s*=\s*)(".*")
      replace: '$url = "{{ url }}"'
    - regwxp: (^\s*[$]*checksumZip\s*=\s*)(".*")
      replace: '$checksumZip = "{{ file_hash }}"'

# readme to description
readme:
  start: 5
  end: 13

# deploy
deploy:
  - provider: chocolatey
    repository: 'https://nuget.itigo.tech/upload'
    key: "{{ lookup('env','CHOCOLATEY_ITIGO_API_KEY') }}"
  - provider: chocolatey
    repository: 'https://push.chocolatey.org/'
    key: "{{ lookup('env','CHOCOLATEY_ORG_API_KEY') }}"
  - provider: github
    name: 'avarins'
    email: 'avarins@sbaerlo.ch'
    url: github.com/sbaerlocher/chocolatey.veeam-agent.git
    key: "{{ lookup('env','GITHUB_API_KEY') }}"

# Notification
notifications:
  - provider: mattermost
    url: 'https://matters.itigo.tech'
    key: "{{ lookup('env','MATTERMOST_API_KEY') }}"
    channel: 'software-packages'
